### ISSUE TITLE
requirements for convert.py

### ISSUE THREAD

**Issue by BaptisteCecconi** [ivoa-std/Vocabularies#11]
It would be good to add the requirements in the README (`skosify`, `rdflib` and `rapper`).

I've installed `rdflib`, `skosify` and `rapper using `pip`, under Python 3.9.

Unfortunately, `rapper` doesn't seem to work properly, but I can't find any documentation associated to that package (the PyPI page doesn't give any information).

**Comment by msdemlei** [comment]
On Tue, Jun 20, 2023 at 08:12:41AM -0700, Baptiste Cecconi wrote:
> It would be good to add the requirements in the README (`skosify`, `rdflib` and `rapper`).
>
> I've installed `rdflib`, `skosify` and `rapper using `pip`, under Python 3.9.
>
> Unfortunately, `rapper` doesn't seem to work properly, but I can't
> find any documentation associated to that package (the PyPI page
> doesn't give any information).

Oh, rapper (which is part of the Debian raptor2-utils package) isn't
a python library.  You'd fetch it from here:
<https://librdf.org/raptor/>.

However, that it's used here at all is just an artefact of
convert.py's ... umm ... provenance.  Since we have python3-rdflib
anyway, writing the RDF/XML directly from python really isn't a big
deal, and hence we should throw out the C dependency.

I promise to write the code for that RSN, but since I don't want to
rush this and there are a few overdue things elsewhere, please give
me a week or two.  Alternatively, I'm grateful if someone else went
for it; since convert.py doesn't actually build a proper triple set
internally, I suppose you'll want to do write_rdfx just the way it's
written now, only using rdflib.  That would look something like this:

  triples = rdflib.Graph()
  with open(self.name+".ttl") as f:
    triples.load_from_file(f)
  with open(self.name+".rdf") as f:
    triples.write_to_rdfx(f)

-- except I'd have to look up what how load_from_file and
write_to_rdfx are actually called and make sure the new result and
the old one are not too different (there are many, many ways in which
you can write RDF/XML) and so on.

**Comment by BaptisteCecconi** [comment]
I managed to install `raptor` after I understand this was the way. So now it works properly.

**Comment by msdemlei** [comment]
Closing since convert.py doesn't depend on raptor any more
